name: Essai 3, Python 3.10.5, requirements.txt ajout de spacy
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10.5
      uses: actions/setup-python@v1
      with:
        python-version: 3.10.5
    - name: Install dependencies
      run: |
        make install
